server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  # DataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://ip/DBname?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: username
    password: passwordDC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    zookeeper:
      connect-string: 101.37.204.222:2181
