server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
      # DataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.37.204.222/sc2020?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: sc2020
    password: 1qaz@WSX#EDC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: 192.168.1.4
      port: 8500
      discovery:
        service-name: ${spring.application.name}
