server:
  port: 80

eureka:
  client:
    #true 表示向注册中心注册自己
    register-with-eureka: false
    service-url:
      # 连接三个eureka服务中心，实现集群的高可用
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

#设置Feign客户端超时时间（OpenFeign默认支持Ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后，从服务器读取到可用资源的所用的额时间
  ConnectTimeout: 5000