server:
  port: 3344

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          #使用https的方式，需要添加用户名密码，如果使用的第SSH的方式，就不需要。
          uri: https://github.com/serug/springcloud2020.git
          username: ******
          password: ******
          #配置search-paths,可以找仓库下的子目录
          search-paths: config-file/3355
      # 读取master分支下的
      label: master

  # RabbitMQ相关配置：连接配置
  rabbitmq:
    host: 192.168.1.4
    port: 5672
    username: guest
    password: guest

# RabbitMQ相关配置：暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"