server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  # DataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.37.204.222/sc2020?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: sc2020
    password: 1qaz@WSX#EDC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #zipkin
  zipkin:
    base-url: http://192.168.1.4:9411
    sleuth:
      sampler:
        #采样率值介于0~1之间，1表示全部采集
      probability: 1


mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: top.serug.springcloud.entities

eureka:
  client:
    # true 表示向注册中心注册自己
    register-with-eureka: true
    # true 需要检索服务
    fetch-registry: true
    service-url:
      # http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: paymentServer8001
    prefer-id-address: false
#    #Eureka客户端向服务端发送心跳包的时间间隔，单位为秒，默认30秒
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳包的大等待时间上限，单位为秒，默认90秒
#    lease-expiration-duration-in-seconds: 2
