server:
  port: 83

spring:
  application:
    name: cloudalibaba-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848

#配置调用的服务名，通过RestTemplate调用时，使用
server-url:
  nacos-user-service: http://nacos-provider-payment
