server:
  port: 9004

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
