server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_get               #路由ID，没有固定规则。要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配提供服务的路由地址,写死的uri
          #动态路由的方式
          uri: lb://CLOUD-PAYMENT-SERVICE  #动态路由的方式
          predicates:
            - Path=/payment/get/**      #断言，路径断言，路径匹配额进行路由

        - id: payment_lb
          #uri: http://localhost:8001   #匹配提供服务的路由地址,写死的uri
          #动态路由的方式
          uri: lb://CLOUD-PAYMENT-SERVICE  #动态路由的方式
          predicates:
            - Path=/payment/lb/**
          filters:
            - name: Example
              args:
                op: root
                type: he


        #这个就是对所有的路径路由
#        - id: payment_all
#          #写死的uri
##          uri: http://localhost:8001
#          #动态路由的方式
#          uri: lb://CLOUD-PAYMENT-SERVICE
#          predicates:
#            - Path=/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

